# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Learning Blog
description: I build data pipelines, machine learning systems, and analytical products, then write clear notes about the engineering choices behind them.
github_username: srujanreddyj

author: Srujan Jabbireddy
#avatar: /logo.png
email: jsrujanreddy@gmail.com


# Email and twitter are optional:
email: jsrujanreddy@gmail.com
twitter_username:
linkedin_username: srujan-reddy 

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-157263530-1

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-theme-hamilton
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-redirect-from

feed:
  excerpt_only: true

paginate: 10

exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
